In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])  
print(arr)

[1 2 3 4 5]


# Numpy
Numpy is a powerful library for numerical computing in python.It provides support of array,matrics and many mathematics operations.

In [1]:
# Numpy arrays
import numpy as np
#creating a 1d array
arr=np.array([1,2,3,4,5])

#creating 2d array
arr2=np.array([[1,2,3],[4,5,6]])
print("1D array",arr)
print('2d array',arr2)


1D array [1 2 3 4 5]
2d array [[1 2 3]
 [4 5 6]]


In [4]:
# Array attribute
# Numpy array have several attribute that give information about the array.

print('shape of arr1:',arr.shape)
print('shape of arr2:',arr2.shape)
print('Number of dimensions of arr2:',arr2.ndim)
print('datatype of arr2',arr2.dtype)
print('size of arr2',arr2.size)



shape of arr1: (5,)
shape of arr2: (2, 3)
Number of dimensions of arr2: 2
datatype of arr2 int64
size of arr2 6


In [5]:
# array intialization
#Numpy provide several function to create array.

#array of zeros
zeros=np.zeros((2,3))

#array of ones
ones=np.ones((2,3))

#array with random values
rand=np.random.rand(2,3)

#array with a range of values
range_arr=np.arange(10)

#array with values spaces evenly on a log scale

logspace_arr=np.logspace(1,2,10)
print("zeros:\n",zeros)
print("ones\n",ones)
print('random values\n',rand)
print('range array:\n:',range_arr)
print('logspace array:\n',logspace_arr)


zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones
 [[1. 1. 1.]
 [1. 1. 1.]]
random values
 [[0.8509155  0.99947171 0.4720762 ]
 [0.92103966 0.20744868 0.27013254]]
range array:
: [0 1 2 3 4 5 6 7 8 9]
logspace array:
 [ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [2]:
# Basic operations.
#Arithmatic Operations.

#Arithmatic operations can be performed on numpy array element wise
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#Addition
add=arr1+arr2

#substraction
sub=arr1-arr2

#Multiplication
mul=arr1*arr2

#Division
div=arr1/arr2

print('addition:',add)
print('substraction',sub)
print('Multiplication',mul)
print('Division',div)

addition: [11 22 33 44 55]
substraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


# Stastical Operations
Numpy provides various function to perform stastistical operations.

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

# minimum and maximum
min_val=np.min(arr)
max_val=np.max(arr)

# Mean
mean_val=np.mean(arr)

# Standard Deviation
std_val=np.std(arr)

# Sum
sum_val=np.sum(arr)
print('Min:',min_val)
print('Max:',max_val)
print("Mean:",mean_val)
print('Standard Deviation:',std_val)
print("Sum",sum_val)



Min: 1
Max: 10
Mean: 5.5
Standard Deviation: 2.8722813232690143
Sum 55


# Advance Numpy
1. **Broadcasting**: Broadcasting allows Numpy to perform element wise operation on array of different shapes.

In [9]:
arr=np.array([1,2,3])
arr2=np.array([[1],[2],[3]])
#Broadcasting example
result=arr+arr2
print(result)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Reshaping Arrays.
We can change the shape of an array using the reshape function.

In [10]:
arr=np.arange(1,13)

# Reshape to 3x4 array
reshaped_arr=arr.reshape((3,4))
print(arr)
print(reshaped_arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Stacking and Splitting Arrays
We can stack and split array using various function.

In [3]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

#Horizontal stack
hstacked=np.hstack((arr1,arr2))

#vertical stack
vstacked=np.vstack((arr1,arr2))

#split arrays
hsplit_arr=np.hsplit(hstacked,2)
vsplit_arr=np.vsplit(vstacked,2)

print(hstacked)
print(vstacked)
print(hsplit_arr)
print(vsplit_arr)


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [4]:
import numpy as np
arr=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

#Horizontal stack
hstacked=np.hstack((arr,arr2))

#vertical stack
vstacked=np.vstack((arr,arr2))

#split arrays
hsplit_arr=np.hsplit(hstacked,2)
vsplit_arr=np.vsplit(vstacked,2)

print(hstacked)
print(vstacked)
print(hsplit_arr)
print(vsplit_arr)


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


# Linear Algebra Operation
Numpy provides support for linear algebra operation

In [17]:
from numpy.linalg import inv,eig
matrix=np.array([[1,2],[3,4]])

#Matrix inverse
inv_matrix=inv(matrix)

#eigenvalues and eigenvectors
eigenvalues,eigenvectors=eig(matrix)
print(matrix)
print(inv_matrix)
print(eigenvalues)
print(eigenvectors)



[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Best practices
- **Use Vectorized Operations**: Avoid loops,use numpy built functions and vectorized operation for better performance.
- **Memory Management**: Be mindful of array sizes and data types to optimize memory usuage.
- **Avoiod copying Data** : use views instead of copies whenever possible to save memory and imporove performance.
- **Use Broadcasting**: Levrage boradcasting to perform operatios on arrays of different shapes with out needing to replicate data.

In [5]:
# Problem:Calculates the pairwise distance between points in 2d space
import numpy as np

#define points in 2d space
points=np.array([[1,2],[3,4],[5,6]])
#calculate the pairwise distances
#(x2-x1)^2+(y2-y1)^2

diff=points[:,np.newaxis,:]-points[np.newaxis,:,:]
squared_diff=diff**2
distances=np.sqrt(squared_diff.sum(axis=2))
print(points)
print(distances)

[[1 2]
 [3 4]
 [5 6]]
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


# Explanation
- **Define Points**: We define a 2D array points where each row is point in 2D space
- **Calculate Differences**: We calculate the differences between each pair of points using broadcasting.
- **Square Differences**: We square the differences to prepare for distance calculation.
- **Sum and Square Root**: We sum the squared differences along the appropriate axis and take the square root to get the distances.

# Broadcasting Rules
**NumPy follows specific rules for broadcasting:**

If the arrays have different numbers of dimensions, the shape of the one with fewer dimensions is padded with ones on its left side.
Arrays are compatible for broadcasting if, for each dimension, the dimension sizes are either the same or one of them is 1.
If the dimension sizes are not the same and none of them is 1, a ValueError is raised.