# In this notebook,we are goint to cover some of the most fundamental concepts of tensors using Tensorflow

## Introdunction to Tesor

In [4]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.16.2


In [5]:
# Create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# check the number of dimensions of a tensor(ndim  stands for number of dimensions)
scalar.ndim

0

In [9]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [10]:
#check the dimension of the vecore
vector.ndim

1

In [11]:
#create a matrix(has more than 1 dimension)
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [12]:
matrix.ndim

2

In [15]:
#create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [16]:
#the number of dimensions
another_matrix.ndim

2

In [21]:
#create a tensor
tensor=tf.constant([[[1,2,3,4]],[[4,5,6,7]],[[7,8,9,10]]])
tensor

<tf.Tensor: shape=(3, 1, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4]],

       [[ 4,  5,  6,  7]],

       [[ 7,  8,  9, 10]]])>

In [22]:
tensor.ndim

3

In [23]:
#what we have created so far:
# scalar: a single number
#vector:a number with direction(e.g. wind speed and directions)
#matrix: a 2-dimensional array of numbers
#tensor:an n-dimensional array of number (when n can be any number,1-dimensional tensor is a vector)

# creating tensor with tf.Variable


In [27]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [30]:
# create the same tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [31]:
#try change one of the elements in our changeable tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [32]:
#the above method is wrong
#the right method below to change the tensor
changeable_tensor[0].assign(8)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 7])>

In [33]:
#try to change the unchangeable tensor
unchangeable_tensor[0]=7
unchangeable_tensor

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

### Creating random tensors
Random tensors are tensors of some arbitary size which contain random numbers