## Numpy Tutorial
- Numpy is a python library.
- Numpy is used for working with arrays.
- Numpy is short for Numerical Python.


## What is Numpy?
- Numpy is a python library used for working with arrays.
- It also has a function for working in domain linear algebra,fourier transform,and matrices.
- Numpy was create in 2005 by travis oliphant.It is an open source project and we can use it freely.
- Numpy stands for Numerical Python.

## Why Use Numpy?
- In Python we have lists that serve the purpose of array,but they are slow to process.
- Numpy aims to provide an array object that is up to 50x faster than traditional python lists.
- The array object in Numpy is called `ndarray`,it provides a lot of supporting functions that make working with `ndarray` very easy.
- Array are very frequently used in data science,where speed and resources are very important.


## Why is Numpy Faster Than Lists?
- Numpy arrays are stored at one continuous place in memory unlike lists,so processes can access and manipulate them very efficiently.
- The behaviour is called locality of reference in computer science.
- This the main reason why Numpy is faster than lists.Also it is optimized to work with latest CPU architectures.

## Installation of Numpy
If we have python and pip already installed on a system,then installation of NumPy is very easy.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy

In [3]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## NumPy as np
Numpy is usually imported under the `np` alias.

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# Checking Numpy version
The version string is stored under `__version__ ` attribute


In [5]:
import numpy as np
print(np.__version__)

1.26.1


## NumPy Creating Arrays
### Create a NumPy ndarray Object
Numpy is used to work with arrays.The array object in NumPy is called `ndarray`.We can create NumPy `ndarray` object by using the `array()` function.

In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**type()**: This built-in python function tell us the type of the object passed to it.Like in above code it shows the `arr` is `numpy.ndarray` type.

- To create an `ndarray` we can pass a list,tuple or any array-like obejct into the `array()` method,and it will be converted into an `array`

In [7]:
# Use a tuple to create a Numpy array.
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


## Dimnsions in arraya
A dimensions in array is one level of array depth(nested array).

**nested array** : are arrays that have arrays as their elements.

## 0-D Arrays
0-D arrays,or scalars are the elements in an arrays.Each value in an array is a 0-D array.

In [8]:
#create a 0-D array with value 42

import numpy as np
arr=np.array(42)
print(arr)

42


## 1-D Array
An array that has 0-D arrays as its element is called uni-dimensional or 1-D array.There are the most common and basic arrays.


In [9]:
# create a 1-D array containing the value 1,2,3,4,5
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## 2-D Array
An array that has 1-D arrays as its element is called 2-D array.These are often used to represent matrix or 2nd order tensors.

`NumPy has a whole sub module dedicated towards matrix operations called numpy.mat`

In [10]:
#create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6

import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


## 3-D arrays
An array that has 2-D array(matrices) as its element is called 3-D array.These are often used to represent a 3rd order tensor.

In [11]:
# create a 3-D arrays with two arrays,both containing 2-D arrays  with the values 1,2,3, and 4,5,6
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check Number of Dimensions
NumPy arrays provides the `ndim` attribute that returns an integer that tells us how many dimensions the array have.


In [12]:
# Check how many dimensions the arrays have

import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)
print(d)
print(d.ndim)

42
0
[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


## Higher Dimensional Arrays
An arrays can have any number of dimensions.When the array is created,we can define the number of dimensions by using the `ndmin` argument.

In [13]:
# create an array with 5 dimensional and verify that it has 5 dimensions.
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


## Numpy array Indexing
### Access array elements
Arrays indexing is the same as accessing an array element.
We can access an array element by referring to its index number.
The indexes in numpy arrays start with 0,meaning that the first element has index 0 and the second has index 1 etc.

In [14]:
#Get the first element from the following way
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [15]:
#get the second element from the following array.
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1])

2


In [16]:
#get third and fourth elements from the following array and add them.
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


## Access 2-D arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the elementn.
- Think of 2-D array like a table with rows and columns,where the dimension represents the row and the index represents the columns.

In [17]:
#Access the element on the first row,second column
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])

2


In [18]:
#Access the element on the 2nd row, 5th column
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,4])

10


## Access 3-D arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [19]:
# Access the third element of the second array of the first array.
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


## Negative Indexing
Use negative indexing to access an array from the end

In [20]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


## NumPy Array Slicing
- Slicing in python means taking elements from one given index to another given index.
- We pass slice instead of index like this :`[start:end]`.
- We can also define the step,like this : `[start:end:step]`.
- If we don't pass start its considered 0.
- If we don't pass end its considered length of array in that information.
- If we don't pass step its considered 1.

In [21]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [22]:
# slice elements from index 4 to the end of the array
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [23]:
#slice elements from the begining to index 4
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


## Negative Slicing
Use the minus operator to refer to an index from the end.

In [24]:
# Slice from the index 3 from the end of index 1 from the end
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


## STEP
Use the `step` value to determine the step of the slicing.

In [25]:
# Return every other element from index 1 to index 5
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [26]:
#return every other element from the entire array
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


## Slicing 2-D arrays
From the second element,slice elements from index 1 to index 4(not include)

In [27]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [28]:
#from both elements,return index2
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [29]:
#From both elements,slice index 1 to 4 index this will return 2-D array.
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


## NumPy Data Types
### Data Types in Python
By default Python have these data types

- `strings`- used to represent text data,the text is given under quote marks. example 'AVBD'
- `integer`- used to represent integer numbers 
- `float`- used to represent real number(1.2,-1.2)
- `boolean`- used to represent True or False.
- `complex`- used to represent complex number. e.g. 1.0 + 2.0j, 1.5 + 2.5j


## Data Types in NumPy
NumPy has some extra data types,and refer to data types with one character like i for integer,u for unsigned integers etc.

- Below is a list of all data types in NumPy and the characters used to represent them.

- `i`-integer
- `b`-boolean
- `u`-unsigned integer
- `f`-float
- `c`-complex float
- `m`-timedelta
- `M`-datetime
- `O`-object
- `S`-string
- `U`-unicode string
- `V`- fixed chunk of memory for other type


## Checking the Data Type of an array
The NumPy array object has a property called `dtype` that returns the data type of the array.

In [30]:
#Get the data type of an array object
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [31]:
#Get the data type of an array containing strings
import numpy as np
arr=np.array(["apple","banana","cherry"])
print(arr.dtype)

<U6


## Creating arrays with a defined data types
We use the `array()` function to create arrays,this function can take an optional argument.`dtype` that allows us to define the expected data type of the array elements.

In [32]:
# Create an array with data type string
import numpy as np
arr=np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [33]:
# create an array with data type 4 byte integer
import numpy as np
arr=np.array([1,2,3,4,5],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


## What if a value can not be converted?
If a type a given in which elements can't be casted then NumPy will raise a Value Error.

**ValueErros** : In python/ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [34]:
# A non integer string like `a` can not be converted to integer(will raise an error)
import numpy as np
arr=np.array(['a','2','3'],dtype='i')
print(arr)

ValueError: invalid literal for int() with base 10: 'a'

## Converting Data Type on Existing Arrays
The best way to change the data type of an existing array,is to make a copy of the array with the `astype()` method.
- The `astype()` function create a copy of the array,and follows to specify the data type as a parameter.
- The data type can be specified using a string like `f` for float,`i` for integer etc.or we can use the data type directly like `float` for float and `int` for integer.


In [ ]:
# Change data type from float to integer by using `i` as parameter value
import numpy as np
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# change data type from float to integer by using int as parameter value.
import numpy as np
arr=np.array([1.1,2.2,3.3])
newarr=arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
#Change data type from integer to boolean
import numpy as np
arr=np.array([1,0,3])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


## NumPy Array Copy vs View
### The Difference Between Copy and View
The main difference between a copy and view of an array is that the copy is a new array and the view is just a view of the origional array.
- The copy owns the data and any changes made to the copy will not affect origional array,and any changes made to the origional array will not affect the copy.
- The view does not own the data and any changes made to the view will affect the origional array,and any changes made to the origional array will affect the view.

In [ ]:
#Make a copy,change the origional array,and display both arrays
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


- The copy SHOULD NOT be affected by the changes made to the origional array.

## View

In [ ]:
#make a view,change the origional array,and display both array
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


## Make Changes in the View
Make a view,change the view,and display both arrays.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
x[0]=31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


## Check if Array Owns its Data
As mentioned above,copy owns the data,and views does not own the data,but how can we check this?
- Every NumPy arrays has a attribute `base` that return `None` if the array owns the data.
- Otherwise ,the `base` attribute refers to the origional object.

In [ ]:
#Print the value of the base attribute to check if an arrya own's its'data or not.
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


## Numpy Array Shape
### Shape of an Array
The shape of an array is the number of elements in each dimensions. 

# Get the Shape of an Array
NumPy arrays have an attribute called `shape` that returns a tuple with each index having the number of corresponding elements.

In [ ]:
# Print the shape of a 2-D array
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


- The example above return (2,4) which means that the array has 2 dimensions,where the first dimensions has 2 element and the scond has 4.

In [ ]:
#create an array with 5 dimensions using `ndmin` using a vector with values 1,2,3,4 and verify that last dimensions has value 4
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


## NumPy Array Reshaping
### Reshaping arrays
Reshaping means changing the shape of an array.
- The shape of an array is the number of elements in each dimensions.
- By reshaping we can add or remove dimensions or change number of elements in each dimensions.

In [ ]:
# Reshape from 1-D to 2-D
#Convert the following 1-D array with 12 elements into a 2-D array.
# The outmost dimension will have 4 arrays,each with 3 elements.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Reshape from 1-D to 3-D
#Convert the following 1-D array with 12 elements into a 3-D arrays.
#The outermost dimension will have 2 arrays that contains 3 arrays,each with 2 elements.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Can We Reshape Into any Shape?
- Yes as long as the elements required for reshaping are equal in both shapes.
- We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D arrays as that would require 3X3=9 elements.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(3,3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
#Returned Copy or View
#Check if the returned array is a copy or a view
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base) # The example above returns the origional array,so it is a view


[1 2 3 4 5 6 7 8]


## Unknown Dimension
- allowed to have one `unknown` dimension.
- Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
- Pass `-1` as the value,and NumPy will calculate this number for you.

In [ ]:
# Convert 1D array with 8 elements to 3D array with 2X2 elements.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Flattening the arrays
Flattening arrays means converting a multidimensional array into 1 D arrays.
- We can use `reshape(-1)` to do this.

In [ ]:
# Convert the array into a 1D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


## Numpy Array Iterating
### Iterating Arrays
Iterating means going through elements one by one
- As we deal with Multi-dimensional array in numpy,we can do this using basic for loop of python.
- If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
#iterate on the elements of the follwing 1-D arrays
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


## Iterating 2-D arrays
In a 2-D array it will go through all the rows


In [ ]:
# Iterate on the elements of the following 2-D arrays
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)


[1 2 3]
[4 5 6]


## If we iterate on a n-D array it will go through n-1th dimension one by one.

- To return the actual value ,the scalars,we have to iterate the arrays in each dimensions.

In [ ]:
# Iterate on each scalar elements of the 2-D arrays
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


## Iterating 3-D arrays
In a 3-D Array it will go through all the 2-D arrays.


In [ ]:
# Iterate on the elements of the followin 3-D arrays
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


- To return the actual values,the scalars,we have to iterate the array in each dimension.


In [ ]:
# Iterate down to the scalars
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


## Iteraing Arrays using nditer()
The function `nditer()` is a helping functions that can be used form very basic to very advanced iterations.It solves some basic issues which we face in iteration,lets go through it with example


## Iterating on each scalar element
In basic `for` loops,iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very dimesnionality.

In [ ]:
# Iterate through the following 3-D arrays
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


## Iterating Arrays With Different Data types
- We can use `op_dtypes` argument and pass it the expected datatype to change the datatype of elements while iterating.
- NumPy does not change the data type of the element in place(where the element is in array) so it needs some other space to perform this actions,that extra space is called buffer,and in order to enable it in `nditer()`we pass `flags=['buffered]`


In [ ]:
#Iterate through the arrays as a string
import numpy as np
arr=np.array([1,2,3])
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


## Iterating With Different Step Size
We cna use filtering and followed by iteration

In [ ]:
#Iterate through every scalar element of the 2D arrays skipping 1 element
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


## Enumerated Iteration Using ndenumerate
Enumeration means mentioning sequence number of something one by one.
- Sometimes we require corresponding index of the element while iterating,the `ndenumerate()` method cna be used for those usecases.

In [ ]:
# Enumerate on the following 1D arrays elements
import numpy as np
arr=np.array([1,2,3])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
# Enumerate on the following 2D arrays elements
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## NumPy Joining Array
### Joining NumPy Arrays
Joining means Putting content of two or more arrays in a single arrays.
- In SQL we Join tables based on a key,wheras in NumPy we join array by axes.
- We pass a sequence of arrays that we want ot join to the `concatenate()` function,along with the axis.If axis is not explicitly passed it,it is taken as 0 .

In [ ]:
# Join two arrays
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
# Join two 2-D array along rows(axis=1)
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Joining Arrays Using Stack Functions
Stacking is same as concatenations,the only difference is that stacking is done along a new axis.
- We can concatenate two 1-D array along the second axis which would result in putting them one over the other i.e stacking.
- We pass a sequence of arrays that we want to join to the `stack()` method along with the axis.If axis is not explicitly passed it is taken as 0.

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


# Stack along rows
Numpy provides a helper function:`hstack()` to stack along rows.


In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


## Stack Along Columns
NumPy provides a helper function:`vstack()` to stakc along columns.

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


## Stacking Along Height(depth)
NumPy provides a helper function:`dstack()` to stack along height,which is the same as depth.

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## NumPy Splitting Array
### Splitting NumPy Arrays
Splitting is reverse operation of joining.
- Joining merges multiple arrays into one and splitting breaks one arrays into multiple
- We use `array_split()` for splitting arrays,We pass it the array we want to split and the number of splits.

In [ ]:
# Split the array in 3 parts
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


-  The return value is a list containing three arrays

In [ ]:
# Split the array in 4 parts
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


- Note: We also have the method `split()` available but it will not adjusts the elements when elements are less in source array for splitting like an example above,`array_split()` worked properly but `split()` would fail.

## Split Into Arrays
The return value of the `array_split()` method is an array containing each of the split as an array.If you split an array into 3 array,we can access them from the result just like any array element.

In [ ]:
# Access the splitted arrays.
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


## Splitting 2-D Arrays
Use the same syntax when splitting 2-D arrays.
- Use the `array_split()`method,pass in the array we want tto split the number of splits we want to do.

In [ ]:
# Split the 2-D array into three 2-D arrays
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
# Split the 2-D arrays into three 2-D arrays
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


- In addition,we can specify which axis we want to do the split around
- The example below alos return three 2-D arrays,but they are split along the row(axis=1)

In [ ]:
#split the 2-D arrays into three 2-D arrays along rows.
import numpy as np
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr=np.array_split(arr,3,axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


- An alternate solution is using `hsplit()` opposite of `hstack()`

In [ ]:
# Use the `hsplit()` method to split the 2-D arrays into three 2-D arrays along rows
import numpy as np
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr=np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## NumPy Searching Arrays
### Searching Arrays
- We can search an array for a certain value,and return the indexes that get a match
- To search an array,use the `where()` method.

In [ ]:
# find the indexes where the values is 4
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [ ]:
# Find the indexes where the values are even
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [ ]:
# Find the indexes where the values are odd
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


## Search Sorted
There is a method called `searchsorted()` which performs a binary search in the array,and returns the index where the specified value would be inserted to maintain the search order.
- The `searchsorted()` method is assumed to be used on sorted arrays.

In [ ]:
# Find the indexes where the values 7 should be inserted
import numpy as np
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7)
print(x)

1


## Search from the Right Side
By default the left most index is returned,but we can give `side=right` to return the right most index instead.

In [ ]:
# Find the indexes where the value 7 should be inserted,starting from the right
import numpy as np
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7,side='right')
print(x)

2


## Multiple values
To search for more than one value,use an array with the specified values

In [ ]:
# Find the indexes where the values 2,4,6 should be inserted
import numpy as np
arr=np.array([1,3,5,7])
x=np.searchsorted(arr,[1,3])
print(x)

[0 1]


## NumPy Sorting Arrays
### Sorting Arrays
Sorting means putting elements in an ordered sequences.
- Ordered sequence is any sequence that has an order corresponding to elements,like numerical or aphabetical,ascending and descending.
- The NumPy ndarray object has a function called `sort()` that will sort a specified arrays.

In [ ]:
# Sort the array
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [ ]:
#We can also sort arrays of strings or any other data type
import numpy as np
arr=np.array(['apple','banana','cherry'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
# Sort a boolean array
import numpy as np
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


In [ ]:
# Sorting a 2-D arrays
import numpy as np
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## NumPy Filter Arrays
### Filter Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.
- In NumPy,we filter an array using a boolean index list.
- If the value at an index is `True` that elements is contained in the filtered array,if the value at the index is `False` that element is excluded from the filtered array.

In [ ]:
# Create an array from the element on index 0 and 2
import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


## Creating the filter array
In the example above we hard-coded the True and False values,but the common use it to create a filter array based on conditions.

In [ ]:
import numpy as np
arr=np.array([41,42,43,44])
#create an empty list
filter_arr=[]

#go through each element in arr
for element in arr:
    #if the element is higher than 42 ,set the value to True,otherwise false
    if element>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
